language: ruby
sudo: false
rvm:
  - 2.2
branches:
  only:
    - master
addons:
  apt:
    packages:
    - lftp
env:
  global:
    - secure: "r/ksd6XrFBdHr7Po2nTaTq+YGAXjG5B84bo4qYPLjDsJ1+7FHHHGtvh10EpOHtR1NExgYWaaHk6wpulVdhJx0BvGxAUZREvhwpC4EUfKzkdAhdL+C5lB8VWaRaYQFMwoJrd/mYgomLKZ2TjVjKg9liUDQ9jFHhiJ2Qrl2XObz1G6ZpoWz5DWly5pSFJr56eq480GpmgfPYs4DHPJMKWEOZbEKKJAQz7bDxHKVtLqVXbOo4X/qQUex+EgHhQNLAuYMbI3WjOffq1WWOj8Hm8YwBz0V+3h9FEYgUDwL7xiUyCd94/5X/AKfeV+cJHrvdJCInvyg41xJtlaIPene0qMHbgUPszIWPdBaHomyj6FWLg9iyObMdWNlndYCuaI0Tjtzyt2PXqMwSbcG/sDmauxHmqAmrjtt3UVhmTRFgN7hmylyYGsQmuhyPGbqNmd+fNRwRhZtaqwXefuqXJHBi0P521yopQc7Ne1KHa7yG5zddKGeIUqcqoR3pPZDRy/cyESH2QGq2UtqxPRGKhdM8nWfwXHTReT6VTs3xRONkdyorzsrZqHeGqMH/tVK9uwY5ZF5CSzkGhxTLsXyoQ7EWI+zBBzrAJ9j0goA6BF9m5uRbIpiuvkGfz3H2HNRXPXBa9dwJ2MA79ourp7tdTCW//HtcHL9O4EYdbgs34KH8PA3e8="
    - secure: "T7Va78wA+n6I4LlqaejkQwKlC4lHJ41G+1sZklYr2NitTuaOFCZeGFSM/qmgyQHAmI1kTxF96VyorrsLoUwe9sRZByfPJh4bijSrDD+R47IpQ0qY2t6vkxfXWlbEQgw+TOybvz8ig1eK4vLdMgqe3avjWAMBLfH77Q6uQ0Z5U3gG+9/i9HpQEpbC2kDk2SDTXhQlKoUqoHNDdi7UoMGcGnUKh00m70rQY+xAQTxTuYCiLMdjFeYaoF2MYOEF9fZMTADYVMTmvb8iioByi7eYuJxyo6zqZb2DGiDrPuRsP8Yw9nS7gJUFM8KUEuRwp8MeihyLcxMm22947L3eFHwWjQsd+2VmCiAjqubpaiRUllDTXjLs/J1E2huhGZgY90l67FeRi/Sa6r606xBHsMeJEjqtea2A74xN4VQm8aeS1Lv8SCeUhsWHZmxigfMdfwp/mCvZJE+XqviTSpX46lfkHEk3K1rz+C948l3slh54xNYqvVxiT7aimMylXw9zSPNFBUH/92pWEEB1nFh7ECtZXbluPACpGSJDDIw37ji6fiBl/y8N/Ch+EWoQArfCbvcGxZB05c/6+Ae4/zyhwfEUalTRC7+oo5RvBTzNW/h53hmUWfeZfW6BTC6eOutRA46RNcOEa2Zozivm9tqkJpVjUZjzZZxaQ8Cp2E/jMDKf1eE="
script:
  - gem install bundler
  - bundle exec jekyll build
after_success:
  - echo set ftp:ssl-force on > ~/.lftprc
  - echo set ftp:ssl-protect-data on >> ~/.lftprc
  - echo set ssl:verify-certificate no >> ~/.lftprc
  - lftp -u $CREDENTIALS $TARGET -e "mirror --exclude proceedings/ --delete --delete-first --verbose -R _site/ .; bye"
