safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
lsi: true
highlighter: rouge
markdown: kramdown
exclude: ['_DOCS', '_SCRIPTS', '.travis.yml', '.travis.d', '.sass-cache', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'LICENSE.md']
sass:
  style: compressed
encoding: UTF-8

url: http://conferences.sigcomm.org
baseurl: /acm-icn/2017/

# Configuration for site
title: ACM ICN 2017
logo:
  image: images/icn17-logo-large.png
  info: ACM ICN 2017, Berlin

google_analytics_id: UA-83529610-1

program:
  # If the specified file doesn't exist, there will be command-line dialog to create it
  google_client_id: .travis.d/google_client_id.json
  # Google spreadsheet with the conference data
  spreadsheet: 1J-lppI-_qcclJbmP3DN_xhgKnJnL6S344BUQQ9JbvIE

# Configuration for navbar.html
menu:
- name: Home
  url: /
- name: Call for Supporters
  url: /cf-supporters.html
# - name: Supporters
#   url: /supporters.html
# - name: Conference
#   submenu:
    # - name: Awards
    #   url: /awards.html
    # - name: Program
    #   url: /program.html
# - name: Program Committee
#   url: /tpc.html
    # - name: Posters
    #   url: /posters.html
    # - name: Demos
    #   url: /demos.html
    # - name: ACM SRC
    #   url: /acm-src.html
    # - name: Industrial Demos
    #   url: /industrial-demos.html
    # - name: Posters/Demos from Main Track
    #   url: /posters-and-demos-main-track.html
    # - name: Topic Preview
    #   url: /topic-preview.html
    # - name: Mentoring
    #   url: /mentoring.html
    # - name: Social Events
    #   url: /social-events.html
# - name: Workshops
#   submenu:
#     - name: TBD
#       url: /tbd.html
# - name: Tutorials
#   submenu:
#     - name: TBD
#       url: /tbd2.html
# - name: Registration
#   url: /registration.html
- name: Local Information
  submenu:
   - name: Venue &amp; Social Events
     url: /venue.html
   - name: City &amp; Travel Tips
     url: /city.html
#     - name: Accommodations
#       url: /accommodations.html
#     - name: Visa Information
#       url: /visa.html
    # - name: Accomodation
    #   url: /hotels.html
    # - name: Room Share
    #   url: /room-share.html
    # - name: Travel Grants
    #   url: /travel-grants.html
    # - name: N2Women Fellowship
    #   url: /n2women-fellowship.html
    # - name: N2Women Travel Grant
    #   url: /n2women-travel-grant.html
- name: Calls
  submenu:
    - name: Call for Papers
      url: /cfp.html
    - name: Submission Details
      url: /submission.html
- name: Organizing Committee
  url: /org-committee.html
# - name: Calls
#   submenu:
#     - name: Call for Papers
#       url: /cfp.html
#     - name: Submission Requirements
#       url: /submission.html
#     # - name: Call for Posters & Demos
#     #   url: /cf-posters.html
#     # - name: Call for Industrial Demos
#     #   url: /cf-industrial-demos.html
#     - name: Call for Tutorials
#       url: /cf-tutorials.html
#     - name: Call for Workshops
#       url: /cf-workshops.html
- name: Policies
  submenu:
    #- name: Author Registration Policy
    #  url: /policy-author-registration.html
    - name: Anti-Harassment Policy
      url: /policy-anti-harassment.html
- name: Previous Editions
  submenu:
    - name: ACM ICN 2016
      url: http://conferences.sigcomm.org/acm-icn/2016/
    - name: ACM ICN 2015
      url: http://conferences.sigcomm.org/acm-icn/2015/
    - name: ACM ICN 2014
      url: http://conferences.sigcomm.org/acm-icn/2014/

colors:
  highlight: 0063A9
  highlight-darker: 3F9E11
  highlightB: 3F9E11
  hfont: FFFFFF

  program:
    break-background: d1d1d1
